---
- name: Update cashe
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installing the necessary software
  apt:
    name:
      - haproxy
      - python3-jinja2
      - python3-paramiko
      - python3-yaml
      - prometheus-node-exporter
    state: present

- name: Creating a HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  become: true
  notify:
    - restart_haproxy
