all:
  children:
    web:
      hosts:
        web1:
          ansible_ssh_user: "{{ vm_user }}"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2222
          ansible_ssh_private_key_file: /home/admin1/course_project/vagrant/.vagrant/machines/web1/virtualbox/private_key
        web2:
          ansible_ssh_user: "{{ vm_user }}"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2200
          ansible_ssh_private_key_file: /home/admin1/course_project/vagrant/.vagrant/machines/web2/virtualbox/private_key
    databases:
      hosts:
        db:
          ansible_ssh_user: "{{ vm_user }}"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2201
          ansible_ssh_private_key_file: /home/admin1/course_project/vagrant/.vagrant/machines/db/virtualbox/private_key
    monitoring:
      hosts:
        prometheus:
          ansible_ssh_user: "{{ vm_user }}"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_private_key_file: /home/admin1/course_project/vagrant/.vagrant/machines/monitoring/virtualbox/private_key
          ansible_ssh_port: 2202
    proxy:
      hosts:
        haproxy:
          ansible_ssh_user: "{{ vm_user }}"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_private_key_file: /home/admin1/course_project/vagrant/.vagrant/machines/haproxy/virtualbox/private_key
          ansible_ssh_port: 2203
    localhost:
      hosts:
        localhost_main:
          ansible_ssh_user: "{{ ansible_user }}"
          ansible_ssh_pass: "{{ ansible_pass }}"
          ansible_ssh_host: 127.0.0.1
          ansible_become_pass: "{{ ansible_pass }}"