all:
  children:
    vagrant:
      hosts:
        web1:
          ansible_user: "vagrant"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2222
          ansible_ssh_private_key_file: {{ key_web1 }}
        web2:
          ansible_user: "vagrant"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2200
          ansible_ssh_private_key_file: /home/admin1/course_project/vagrant/.vagrant/machines/web2/virtualbox/private_key
        db:
          ansible_user: "vagrant"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2201
          ansible_ssh_private_key_file: /home/admin1/course_project/vagrant/.vagrant/machines/db/virtualbox/private_key
        monitoring:
          ansible_user: "vagrant"
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_private_key_file: /home/admin1/course_project/vagrant/.vagrant/machines/monitoring/virtualbox/private_key
          ansible_ssh_port: 2202