---
- name: Update cashe
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installing the necessary packages
  apt:
    name:
      - nginx
      - php-fpm
      - php-mysql
      - php-cli
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
      - mysql-client
      - unzip
      - wget
      - prometheus-node-exporter
    state: present

- name: Make sure nginx is running and enabled at boot
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Make sure php-fpm is running and enabled at boot
  systemd:
    name: php7.4-fpm
    state: started
    enabled: yes

- name: Downloading the latest version of WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0640'

- name: Unpacking the WordPress archive
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Configuring nginx for WordPress
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf

- name: Enabling a WordPress site
  file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-enabled/wordpress.conf
    state: link

- name: Setting up a WordPress Database Connection
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: delete the default site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart_nginx
