global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'

  - job_name: 'db'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.31.102:9100' ]

  - job_name: 'web1'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.31.100:9100' ]

  - job_name: 'web2'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.31.101:9100' ]

  - job_name: 'haproxy'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.31.104:9100' ]