---
- name: Update cashe
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installing dependencies
  apt:
    name:
      - curl
      - wget
      - tar
    state: present


- name: Installing the specified Prometheus version
  block:
    - name: Downloading the Prometheus archive from GitHub
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz
        mode: '0644'

    - name: Unpacking the archive
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/prometheus

    - name: Creating a symbolic link to the Prometheus directory
      ansible.builtin.file:
        src: /opt/prometheus-2.45.0.linux-amd64
        dest: /opt/prometheus
        state: link
        owner: vagrant

- name: Creating directories for configuration
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    owner: vagrant
    mode: '0755'

- name: Creating a logging directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    owner: vagrant
    mode: '0755'

- name: Copying the prometheus.yml configuration file
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: vagrant
    mode: '0644'

- name: Creating a systemd service
  ansible.builtin.copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: Configuring and launching the Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

  #Install grafana

- name: installing grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_10.0.1_amd64.deb

- name: setting up the grafana service
  ansible.builtin.systemd:
    name: grafana-server.service
    state: started
    enabled: yes
    daemon_reload: yes

